baseURL = "https://linuxsuren.github.io/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "SuRenPi"
theme = "gohugoTheme"

googleAnalytics = "UA-4216293-5"

# sectionPagesMenu = "blog"

[languages]
  [languages.zh]
    weight = 1
    languageName = "中文"
  [languages.en]
    languageCode = "en-US"
    weight = 2
    languageName = "English"
    [[languages.en.menu.global]]
      name = "Blog"
      weight = 100
      identifier = "blog"
      url = "/en/blog"
    [[languages.en.menu.global]]
      name = "OpenSource"
      weight = 300
      identifier = "opensource"
      url = "/en/opensource"

[[menu.global]]
  name = "博客"
  weight = 100
  identifier = "blog"
  url = "/blog"
[[menu.global]]
  name = "翻译"
  weight = 200
  identifier = "translation"
  url = "/translation"
[[menu.global]]
  name = "开源"
  weight = 300
  identifier = "opensource"
  url = "/opensource"

[[menu.blog]]
  name = "DevOps"
  weight = 110
  identifier = "devops"
  url = "/blog/devops"
[[menu.blog]]
  name = "编程语言"
  weight = 120
  identifier = "language"
  url = "/blog/language"
[[menu.blog]]
  name = "操作系统"
  weight = 140
  identifier = "os"
  url = "/blog/os"
[[menu.blog]]
  name = "其他内容"
  weight = 180
  identifier = "other"
  url = "/blog/other"

[[menu.global]]
  name = "SuRen"
  weight = 3100
  identifier = "suren"
  post = "external"
  url = "http://blog.surenpi.com"

[[menu.global]]
  name = "Jenkins 中文社区"
  weight = 4100
  identifier = "jenkins"
  post = "external"
  url = "https://jenkins-zh.github.io/wechat"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
section = [ "HTML", "RSS"]

# [mediaTypes]
# [mediaTypes."text/netlify"]
# suffix = ""
# delimiter = ""

# [outputFormats]
# [outputFormats.REDIR]
# mediatype = "text/netlify"
# baseName = "_redirects"
# isPlainText = true
# notAlternative = true
# [outputFormats.HEADERS]
# mediatype = "text/netlify"
# baseName = "_headers"
# isPlainText = true
# notAlternative = true

[blackfriday]
# hrefTargetBlank = true

[related]

threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

[params]
## Gh repo for site footer (include trailing slash)
ghrepo = "https://github.com/linuxsuren/surenpi/"
## GH Repo for filing a new issue
github_repo = "https://github.com/linuxsuren/surenpi/issues/new"
ghdocsrepo = "https://github.com/LinuxSuRen/surenpi/tree/master"

[params.comments.utterances]
enable = true
issueTerm = "pathname"

[params.comments.utterances.github]
username = "linuxsuren"
repository = "linuxsuren/linuxsuren.github.io"

[params.build]
icon = "http://jenkins.k8s.surenpi.com/buildStatus/icon?job=surenpi%2Fmaster"
link = "http://jenkins.k8s.surenpi.com/job/surenpi/job/master/"

[Social]
twitter = "suren69811254"
github = "LinuxSuRen"
sinaweibo = "linuxsuren"
