baseURL = "http://example.org/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "SuRenPi"
theme = "gohugoTheme"

googleAnalytics = "UA-4216293-5"

[[menu.global]]
  name = "博客"
	weight = 100
	identifier = "blog"
	url = "/blog"
[[menu.global]]
  name = "翻译"
	weight = 200
	identifier = "translation"
	url = "/translation"
[[menu.global]]
  name = "开源"
	weight = 300
	identifier = "opensource"
	url = "/opensource"

[[menu.translation]]
  name = "Jenkins"
	weight = 2100
	identifier = "jenkins"
	url = "/jenkins"

[outputs]
home = [ "HTML", "RSS", "REDIR", "HEADERS" ]
section = [ "HTML", "RSS"]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[related]

threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
